# Generated by Django 5.2.7 on 2025-10-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='classes', to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.section'),
        ),
    ]
