# Generated by Django 5.2.7 on 2025-10-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_section_teachers_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
